bidding/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  get 'register', to: 'users#new'
  post 'register', to: 'users#create'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :products
  root 'products#index'
end

bidding/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user

  def update_bid(bid_params)
    if current_bid * 1.1 <= bid_params[:current_bid].to_d
      self.current_bid = bid_params[:current_bid].to_d
    else
      false
    end
  end
end

bidding/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 128 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }

  has_many :products
  has_secure_password

  def fullname
    "#{first_name} #{last_name}"
  end

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

bidding/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

bidding/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout :user_layout

  def index
    @products = Product.all

    respond_to do |format|
      format.html { @products }
      format.json { render json: @products }
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to product_path(@product.id)
    else
      redirect_to new_product_path
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.users_id == current_user.id
      flash[:notice] = 'You cannot bid, since you are already in the lead.'
      render :edit
    else
      @product.users_id = current_user.id
      @product.bidder_name = current_user.fullname

      if @product.update_bid(bid_params)
        if @product.save
          render :show
        else
          flash[:notice] = 'Bid unsuccessful.'
          render :edit
        end
      else
        flash[:notice] = 'Bid must be atleast 10% higher than the last.'
        render :edit
      end
    end
  end

  private

  def bid_params
    params.require(:product)
          .permit(:current_bid)
  end

  def product_params
    params.require(:product)
          .permit(:name, :description,
                  :current_bid)
  end

  def user_layout
    logged_in? ? 'user' : 'application'
  end
end

bidding/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user&&@user.authenticate(params[:session][:password])
      log_in @user
      # params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      render 'users/log_in'
    else
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to '/products'
  end
end

bidding/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to '/products'
    else
      render :new
    end
  end

  def show
    render :log_in
  end

  private

  def user_params
    params.require(:user)
          .permit(:first_name, :last_name,
                  :email, :password, :password_confirmation,
                  :address, :phone_number)
  end
end

bidding/app/helpers/application_helper.rb
module ApplicationHelper
end

bidding/app/helpers/products_helper.rb
module ProductsHelper
end

bidding/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

bidding/app/helpers/users_helper.rb
module UsersHelper
end

bidding/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bidding</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="main-container" class="container-fluid">
    <div class="row">
      <div id="sidebar" class="col-xs-0 center-block">
        <!-- sidebar content -->
        <nav class="navbar navbar-default" role="navigation">
          <span> <a class="navbar-brand" href='http://localhost:3000/login'>Login</a> </span>
          <span> <a class="navbar-brand" href='http://localhost:3000/products'>Products</a> </span>
          <span> <a class="navbar-brand" href='http://localhost:3000/register'>Register</a> <span>
        </nav>
      </div>
        <div id="content" class="col-xs-8">
        <!-- main content -->
        <%= yield %>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

bidding/app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bidding</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="main-container" class="container-fluid">
    <div class="row">
      <div id="sidebar" class="col-xs-0 center-block">
        <!-- sidebar content -->
        <nav class="navbar navbar-default" role="navigation">
          <span> <a class="navbar-brand" href='#'><%= current_user.fullname %></span>
          <span> <a class="navbar-brand" href='http://localhost:3000/products'>Products</a> </span>
        </nav>
      </div>
        <div id="content" class="col-xs-8">
        <!-- main content -->
        <%= yield %>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

bidding/app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name, class: 'form_control'%><br/>

  <%= f.label :description %>:
  <%= f.text_field :description, class: 'form_control'%><br/>

  <%= f.label :current_bid %>:
  <%= f.text_field :current_bid, class: 'form_control'%><br/>

  <%= f.submit "Create", class: "btn btn-primary"%>
<% end %>

bidding/app/views/products/_product.html.erb
<div class="product item-<%= product.id %>">
<h3><%= product.name %></h3>
<br>
<% if logged_in? %>
  <span><a href=<%= "/products/#{product.id}/edit" %> class="btn btn-primary pull-right">Bid</a></span>
<% end %>
<% if product.users_id && product.bidder_name %>
  Latest bid made by: <span class="bidder"><%= product.bidder_name %></span>
<% end %>
<span class="btn btn-primary pull-right bid-price"><%=product.current_bid%></span>
<h3>Description: <small><%= product.description %></small><h3>
</div>

bidding/app/views/products/edit.html.erb
<%if flash[:notice]%>
	<p><%= flash[:notice]%></p>
<%end%>

<%= form_for @product do |f| %>

  <%= f.label "Enter bid: " %>
  <%= f.text_field :current_bid, class: 'form_control' %><br/>

  <%= f.submit "Make bid.", class: "btn btn-primary" %>
<% end %>

bidding/app/views/products/index.html.erb
<% @products.each do |product| %>
  <a href="/products/<%= product.id %>">
  <div id="wrapper">
    <section>
      <%= render partial: "product", locals: { product: product } %>
    </section><br>
  </div>
  <br>
  </a>
<% end %>

bidding/app/views/products/index.js.erb
$('#products').html("<%= escape_javascript(render(partial: product))")

bidding/app/views/products/new.html.erb
<%if flash[:bad_input]%>
	<p><%= flash[:bad_input]%></p>
<%end%>

<%= render 'form' %>

bidding/app/views/products/show.html.erb
<div id="show">
  <%= render partial: "product", locals: { product: @product } %>
</div>

bidding/app/views/users/log_in.html.erb
<h1> Welcome </h1>
<h1><%= @user.first_name %> <%= @user.last_name %></h1>
<%= link_to 'Log out!', logout_path, :method => :delete %>

bidding/app/views/users/new.html.erb
<%= form_for(:user, url: register_path) do |f| %>
  <%= f.label :first_name %>:
  <%= f.text_field :first_name, class: 'form-control'%><br/>

  <%= f.label :last_name %>:
  <%= f.text_field :last_name, class: 'form-control' %><br/>

  <%= f.label :email %>:
  <%= f.email_field :email, class: 'form-control' %><br/>

  <%= f.label :password %>:
  <%= f.password_field :password, class: 'form-control' %><br/>

  <%= f.label :password_confirmation %>:
  <%= f.password_field :password_confirmation, class: 'form-control' %><br/>

  <%= f.label :address %>:
  <%= f.text_field :address, class: 'form-control' %><br/>

  <%= f.label :phone_number %>:
  <%= f.text_field :phone_number, class: 'form-control' %><br/>
  <%= f.submit "Register me", class: "btn btn-primary"%>
<% end %>